name: Build Kernel Star Hyper A14

on:
  workflow_dispatch:
    inputs:
      PROFILE_NAME:
        description: "Arquivo em Profiles/ (ex.: star_hyper_a14.env)"
        required: true
        default: "star_hyper_a14.env"

jobs:
  ping:
    runs-on: ubuntu-22.04
    steps:
      - name: Ok, o Actions reconheceu
        run: echo "Workflow OK 🎯"
